@startuml 管理者側ドメインモデル図（出荷通知付き）
skinparam componentStyle rectangle
 
' 管理者を中心としたモデル構造
[管理者] o-- [管理アカウント]
[管理者] o-- [商品管理]
[管理者] o-- [注文管理]
[管理者] o-- [返品処理]
[管理者] o-- [出荷処理]
 
[管理者] o-- [権限種別]
[商品管理] o-- [商品操作種別]
[出荷処理] o-- [メール送信]
 
@enduml