@startuml 顧客側ドメインモデル図（コンポーネントスタイル）
skinparam componentStyle rectangle
 
' 顧客を中心としたモデル
[顧客] o-- [アカウント]
[アカウント] o-- [セッション]
[セッション] o-- [セッション状態]
 
[顧客] o-- [注文]
[注文] o-- [注文状態]
[注文] o-- [注文明細]
[注文] o-- [支払い]
[注文] o-- [発送]
[注文] o-- [返品申請]
 
[注文明細] o-- [商品]
[支払い] o-- [支払い方法]
[発送] o-- [発送状態]
 
@enduml