@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName:String
 -mytime:int
 -goodMorning:String
 -goodAfernoon:String
 -goodNight:String
 -firstValue:int
 -secondValue:int
 -resuit:int

 +getMyName():String
 +setNewName():int
 +setNewTime():void
 +getMyGreeting():String
 +setFirstvalue():void
 +setSecondtvalue():void
 +足し算結果登録():void
 +getAddition():int
}

@enduml
